[project]
name = "learningfastmcp"
version = "0.1.0"
description = "Learning project for MCP and FastMCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=3.0.1",
]